### ISSUE TITLE
detect duplicate properties

### ISSUE THREAD

**Issue by delanym** [Ekryd/sortpom#104]
While you're sorting tags, could you emit a warning for duplicate properties? For example,

```
<properties>
  <cglib>3.2.4</cglib>
  <cglib>3.2.0</cglib>
<properties>
```

**Comment by Ekryd** [comment]
Hi,
The purpose of the SortPom plugin is not to validate pom files (unless it is sorting related). I think that a PR to the Maven Enforcer plugin (or similar plugin) is more appropriate. I think that most IDE's warn for this as well.
Regards, Björn
