### ISSUE TITLE
sortDependencies should have an option to leave the order of "import" scope dependencies alone

### ISSUE THREAD

**Issue by franck102** [Ekryd/sortpom#124]
Most often we do want dependencies sorted, and this usually doesn't have any semantic consequences except...

... for imported BOMs, since if an artifact version is declared in multiple imported BOMs the first BOM listed will win. We typically use this to override versions in thrid-party BOMs, e.g.:
<import our-bom>            # may contain jackson.x.y: 2.0 
<import jersey-bom>.      # may contain jackson.x.y: 1.0

The order in the POM for other scopes normally doesn't matter much so we would still like to see them sorted by groupid/artifactId.

An option to sort dependencies like today, but while preserving the order of import scope dependencies, would be great!

**Comment by Ekryd** [comment]
Hi, 
A parameter to leave stuff alone is actually quite hard. But you have the option to use ignored sections for your use case. Have a look at https://github.com/Ekryd/sortpom/wiki/IgnoringSections and please let me know if that helps you

**Comment by franck102** [comment]
An ignored section should work perfectly here, thanks!
