### ISSUE TITLE
Add blank lines

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ekryd/sortpom#14]
```
The configuration has an option to preserve blank lines, but have you 
considered adding an option to add blank lines when they don't exist (in order 
to match the blank lines that exist in the sort order file)?

```

Original issue reported on code.google.com by `as976...@gmail.com` on 12 Sep 2012 at 6:44

**Comment by ddcruver** [comment]
Do we have plans to implement this feature?

**Comment by Ekryd** [comment]
Hi,
There are no plans to implement this feature. Existing bank lines can be preserved with the "keepBlankLines" option. I suggest to format the pom as you l prefer it and then always perform the sorting with the "keepBlankLines" option.
You are very welcome to submit a pull request to solve this issue.
