### ISSUE TITLE
How install as an IntelliJ plugin?

### ISSUE THREAD

**Issue by boardtc** [Ekryd/sortpom#150]
I can't update my pom to add this plugin and just want to run it as a once-off manually.

There are no instructions on how to install the plugin if not adding to your pom. Since it's not in the marketplace I selected to install from disk in IntelliJ, this gives the message:

`Fail to load plugin descriptor from file sortpom-sortpom-parent-3.0.0.zip`

How can I get it installed in IntelliJ?

**Comment by Ekryd** [comment]
Hi!
The plugin can only be run through Maven. It has no functionality to be run separately as a pure Java program or directly as an IntelliJ plugin.

The standalone terminal way to run it (through Maven) is:
`mvn com.github.ekryd.sortpom:sortpom-maven-plugin:3.0.0:sort -Dsort.predefinedSortOrder=custom_1`
Set your desired parameters according to https://github.com/Ekryd/sortpom/wiki/Parameters 

I use IntelliJ myself, but haven't installed a standalone tool in it. One way to do it, is to run the plugin in the Terminal tab as needed. SortPom is not an IntelliJ plugin, so it is not possible to install it directly in the Plugins settings.

Any special reason that the plugin cannot be added to the pom file?
