### ISSUE TITLE
Sortpom deleted the first blank line

### ISSUE THREAD

**Issue by longtai-cn** [Ekryd/sortpom#195]
## Questions raised

Hello, I use `spotless` to build `sortpom `. I want to ask how to solve the problem of deleting empty lines.

## Reproduction steps

pom

```xml
<plugin>
    <groupId>com.diffplug.spotless</groupId>
    <artifactId>spotless-maven-plugin</artifactId>
    <version>2.22.1</version>
    <configuration>
        <pom>
            <sortPom>
                <encoding>UTF-8</encoding>
                <nrOfIndentSpace>4</nrOfIndentSpace>
                <keepBlankLines>true</keepBlankLines>
                <indentBlankLines>true</indentBlankLines>
                <indentSchemaLocation>true</indentSchemaLocation>
                <spaceBeforeCloseEmptyElement>true</spaceBeforeCloseEmptyElement>
                <sortModules>false</sortModules>
                <sortExecutions>false</sortExecutions>
                <expandEmptyElements>false</expandEmptyElements>
            </sortPom>
        </pom>
    </configuration>
</plugin>
```

execute

```shell
mvn spotless:apply
```

## After execution

![image](https://user-images.githubusercontent.com/77398366/165415339-3b5cb5a5-57fc-4431-8117-a25b38b34e0a.png)

## anticipate result

The spaces in the first line are not deleted

**Comment by Ekryd** [comment]
Hi! My first guess is that Sortpom assumes that the copyright notice on top is comment to the `project` element and therefore groups them together. Is this problem cosmetic or does it cause other issues down the line?

**Comment by longtai-cn** [comment]
@Ekryd It won't cause compilation problems, but I want empty lines not to be deleted. What should I do.

**Comment by Ekryd** [comment]
Sorry, I made a few tests and the copyright notice is indeed treated as any other comment in the xml file. Comment are always placed on the line before the element, so no blank lines in between. There is currently no way of keeping extra blank lines between a comment and the element.
By the way, why are you keeping a copyright notice inside the pom file? The build file usually doesn't contain business logic. Also it is easier to letting the whole repo just have one licence file (similar to mine [LICENSE.md](https://github.com/Ekryd/sortpom/blob/master/LICENSE.md))

**Comment by longtai-cn** [comment]
why are you keeping a copyright notice inside the pom file?
-- This is part of the project specification.

By the way, are you going to enhance this, such as giving users an option to choose whether to leave blank lines on the <project> tab.

**Comment by Ekryd** [comment]
No plans for this enhancement. Feel free to submit a PR

**Comment by longtai-cn** [comment]
Thank you for your reply
