### ISSUE TITLE
License Header is removed from 3.1.0 release

### ISSUE THREAD

**Issue by hazendaz** [Ekryd/sortpom#205]
I looked over the change log but not seeing any direct mention of what has occurred.  My best guess is that something in the jdom 2 upgrade.  With 3.0.1, license header in pom.xml is left alone.  In 3.1.0, it is deleted.  Was this intential?  Is there some way to work around the issue?

**Comment by hazendaz** [comment]
sure you can run it against this https://github.com/hazendaz/base-parent/blob/master/pom.xml with simple sortpom:sort which Results in license header removal which is just a comment.

![image](https://user-images.githubusercontent.com/975267/169879260-8e40be64-df59-4aa1-a788-f46bb6bb06d2.png)

**Comment by dwalluck** [comment]
I see also that `<ignore />` has been changed to `<ignore/>`. I think that as a general rule, sortpom should not modify any kind of whitespace, unless it's also meant to be a code formatting tool.

**Comment by hazendaz** [comment]
@dwalluck the 'ignore' can be ignored.  I didn't run it with parameters that would not do that.  My only issue is the license header is being removed.  If I ran all the parameters I use it would have left that bit alone.  The example here was just for a quick project to look at that shows the issue.

**Comment by hazendaz** [comment]
@dwalluck Use ```<spaceBeforeCloseEmptyElement>true</spaceBeforeCloseEmptyElement>``` to ensure the whitespace change doesn't occur.  Sorry didn't have that in my example.  I have updated my config to include that and re-ran to show the proper screen shot of the consideration on this issue.

![image](https://user-images.githubusercontent.com/975267/169923981-161d0a1c-76c3-40d2-953e-514f5907322c.png)

**Comment by hazendaz** [comment]
I had not changed anything either.  The repo I saw this on first is not public.  So I added a quick check on one I have that is public that did not use same configuration.  If i recall, that configuration with the whitespace removal actually changed with 3.0.0 of this plugin.

**Comment by Ekryd** [comment]
Thanks for the example. Removing the comment sounds suspicious. I’ll have a look at it.

**Comment by Ekryd** [comment]
This is a problem. When the root element is added to a newly created xml document, all content is cleared (including the comment). I will work on a fix as soon as possible.

**Comment by Ekryd** [comment]
Found the problem. Will issue a new version

**Comment by Ekryd** [comment]
This should be fixed with version 3.1.1. @hazendaz please try it out and report if it fixes your problem

**Comment by hazendaz** [comment]
Confirmed fixed.  Thank you!

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dwalluck** [comment]
Fixed for me, too.

**Comment by Ekryd** [comment]
Great! I hope that you are satisfied with SortPom and thanks for reporting the issue
