### ISSUE TITLE
Whitespace after XML comments removed since 3.1.0 release

### ISSUE THREAD

**Issue by Stephan202** [Ekryd/sortpom#209]
Following resolution of #206, the the 3.1.x releases drop whitespace in one more case, namely after XML comments.

To reproduce, run:
```sh
git clone git@github.com:PicnicSupermarket/oss-parent.git
cd oss-parent
git checkout origin/master
mvn com.github.ekryd.sortpom:sortpom-maven-plugin:3.0.1:sort
git commit -m 'Before' pom.xml
mvn com.github.ekryd.sortpom:sortpom-maven-plugin:3.1.2:sort
git diff
```

**Comment by Ekryd** [comment]
Hi! i will look into this

**Comment by Ekryd** [comment]
Couldn't find the pom.xml. Do you paste the comment section that fails?

**Comment by Ekryd** [comment]
```
<!-- The test JVMs are short-running. By disabling certain
            expensive JIT optimizations we actually speed up most tests. -->
            -XX:TieredStopAtLevel=1
```
to
```
<!-- The test JVMs are short-running. By disabling certain
            expensive JIT optimizations we actually speed up most tests. -->-XX:TieredStopAtLevel=1
```
I see, need to dig a little deeper

**Comment by Ekryd** [comment]
WIth the new XML framework, text is always trimmed because it it placed within two elements.
In this case it is preceded by a comment, that always start at a new line.
This do create a strange mix of comments (that start on new lines) and text which is trimmed (so it stays on the same line)

**Comment by Ekryd** [comment]
I have found a way to always place text nodes, which have siblings (such as a comment), on their own line. 
The problem is that I don't know if this is going to cause other problems in other pom files.
This behaviour may perhaps be toggled with some sort of parameter.

**Comment by Stephan202** [comment]
@Ekryd Tnx for jumping on this so quickly! I built the branch and tested it against another internal repo: the results look exactly as expected :tada:

**Comment by Ekryd** [comment]
Hi! Version 3.1.3 should solve your problem, try it and report how it works.

**Comment by Stephan202** [comment]
Tnx for the rapid new release! The upgrade build against our internal repository passes :rocket:
