### ISSUE TITLE
Suggestion: Add a parameter to control the sort of dependencies in dependencymanagement

### ISSUE THREAD

**Issue by ssquan** [Ekryd/sortpom#210]
If someone wants dependencies to be sorted first by `scope` in `dependencies`, but `groupId` in `dependencyManagement`, they will need a parameter independent of `sortDependencies`.
I would like to create a pull request for this.

**Comment by Ekryd** [comment]
Interesting! What it the use case?
Would it be some kind of `sortDependencyManagements` (or `sortManagementDependencies`) param that would take precedence if present and would fallback `sortDependencies` if not present?

You are always welcome to create a PR. Be aware that I try to stay at 100% test coverage and I have an integration test for each parameter.

**Comment by ssquan** [comment]
> 

The common case is someone controls the version of dependency by BOMs but doesn't declare scope in the `dependencyMangement` section. In this case,  dependencies in the `dependencyMangement` section should be sorted first by some element not `socpe` such as `groupId` since there is no `scope` at all.

Declare `scope` in `dependencyMangement` is not a good practice. Here is a discussion in stackoverflow :https://stackoverflow.com/questions/15221299/dependencymanagement-and-scope

**Comment by Ekryd** [comment]
Couldn't that be fixed by setting sort to `scope, groupId, artifactId`? If there is not scope, then the plugin wouldn't care about and just sort by the next listed sort criteria.

**Comment by Ekryd** [comment]
I fixed the integration test and added a few test cases. Just discovered that we need this precise functionality; to sort all dependencies but not dependencyManagement all (due to bom conflicts).
Our configuration will look like this:
```
            <sortDependencies>scope,groupId,artifactId</sortDependencies>
            <sortDependencyManagement>none</sortDependencyManagement>
```
I'll try to merge it proptly

**Comment by Ekryd** [comment]
New version 3.2.0 is released. Enjoy!
