### ISSUE TITLE
Minimal version of Java for this plugin ?

### ISSUE THREAD

**Issue by sbernard31** [Ekryd/sortpom#225]
Sorry if I missed it but I didn't find any information about minimal java version required ?

The [pom.xml](https://github.com/Ekryd/sortpom/blob/b31a0308c95f5f8b920926f5962a106977e783d4/pom.xml#L289-L291) seems to say it's java8. Some issues also go in that way : https://github.com/Ekryd/sortpom/issues/35

But when I try to use it, I get : 
```
Execution default-cli of goal com.github.ekryd.sortpom:sortpom-maven-plugin:3.1.3:sort failed: 

Unable to load the mojo 'sort' in the plugin 'com.github.ekryd.sortpom:sortpom-maven-plugin:3.1.3' 
due to an API incompatibility: 

org.codehaus.plexus.component.repository.exception.ComponentLookupException: sortpom/SortMojo has been compiled 
by a more recent version of the Java Runtime (class file version 55.0), 
this version of the Java Runtime only recognizes class file versions up to 52.0
```

Like if code was compiled for java 11 (API version 55.0)

So maybe this is just a mistake about jdk used to compile the released jar ?

(I will maybe use this plugin but my project target java8 and I don't want to go with maven toolchain just for that)

**Comment by Ekryd** [comment]
Hi! SortPom version 3.0.1 supports Java 8, but 3.1.0 and forward has Java 11 as minimum requirement. Oracle dropped the support for Java 8 on March 2022 and there are quite a few new features in 11 to use, so I discontinued the support for 8.
I usually try to follow the support plan from Oracle:
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by sbernard31** [comment]
Thx for the quick answer :pray: 

> Oracle dropped the support for Java 8 on March 2022 

Yep but extended to December 2030.

I will maybe try the 3.0.1 version, hoping there is not blocking issue for me :)

**Comment by Ekryd** [comment]
Don’t think there are any major features. You can check the version history section in the readme. 
Btw, Is it company policy or something else that stops you from using later versions of Java? Personally, I am longing for java 17 at work (we are using 11 now)

**Comment by Ekryd** [comment]
That is food for thought. Maybe I will reevaluate the Java 11 for this plugin. Perhaps I have some time this summer to see how much work it is. Thanks for the input!

**Comment by sbernard31** [comment]
Thx for giving it a try :pray: !

About :
> The new version of dom4j dependency needs 11 or higher. This replaced the old version of JDom 1 which had a security vulnerability that couldn't be fixed.

Does it means that [dom4j site web](https://dom4j.github.io/) must be updated ?  (it says Java 8)
