### ISSUE TITLE
Is it normal that pom.xml in target repository is checked ?

### ISSUE THREAD

**Issue by sbernard31** [Ekryd/sortpom#229]
I use v3.0.1 because of #225 

I add this to my project : 
```xml
  <build>
    <plugins>
      <plugin>
        <groupId>com.github.ekryd.sortpom</groupId>
        <artifactId>sortpom-maven-plugin</artifactId>
        <configuration>
          <createBackupFile>false</createBackupFile>
          <lineSeparator>${leshan.lineseparator}</lineSeparator>
          <verifyFail>stop</verifyFail>
          <verifyFailOn>Strict</verifyFailOn>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

When launching : `mvn com.github.ekryd.sortpom:sortpom-maven-plugin:verify` all seems OK
but when launching : `mvn clean install`
```
[INFO] --- sortpom-maven-plugin:3.0.1:verify (default) @ leshan-core ---
[INFO] Verifying file /home/sbernard/git/leshan/leshan-core/target/leshan-core-2.0.0-SNAPSHOT.pom
[ERROR] The line 21 is not considered sorted, should be '<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">'
[ERROR] The file /home/sbernard/git/leshan/leshan-core/target/leshan-core-2.0.0-SNAPSHOT.pom is not sorted
```

My explanation is that : 
`mvn com.github.ekryd.sortpom:sortpom-maven-plugin:verify` only check pom.xml from source directory.  
but `mvn clean install` checks  `target/leshan-core-2.0.0-SNAPSHOT.pom` which means build directory and not source directory.

In my case I use [flatten-maven-plugin](https://www.mojohaus.org/flatten-maven-plugin/) which change the pom.xml.

I would like to only check the source pom.xml file in source directory not the generated one in build directory. 

Is there a way to do that or maybe I did something wrong ?

**Comment by Ekryd** [comment]
Hi! I am busy the following days, so it will take some time before I can look at this for real. Thanks for your patience. 
ps. it should be the source but but I haven’t experienced your problem. Is it possible to recreate in an integration test?

**Comment by sbernard31** [comment]
I will maybe find time to create an integration test that but not sure.

Waiting you could use : https://github.com/sbernard31/leshan/pull/11 to reproduce that.

**Comment by Ekryd** [comment]
Thanks!

**Comment by sbernard31** [comment]
I digged a little more about this.

**Explanation about why it is called twice ?**
I find why the `sortpom:verify` goal (attached to `validate` phase by default) is called twice.

This is because my build also run  [`maven-source-plugin:jar`](https://maven.apache.org/plugins/maven-source-plugin/jar-mojo.html) goal which : 
>  - Binds by default to the [lifecycle phase](http://maven.apache.org/ref/current/maven-core/lifecycles.html): package.
> - Invokes the execution of the [lifecycle phase](http://maven.apache.org/ref/current/maven-core/lifecycles.html) generate-sources prior to executing itself.

**First try** to fix it :
To attach `sortpom:verify` goal to [`process-sources`](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#default-lifecycle), this way `maven-source-plugin` will execute `generate-sources` and will not recall it.   
==> It seems to work :heavy_check_mark: 

**Second try** to fix it :
Using [`maven-source-plugin:jar-no-fork`](https://maven.apache.org/plugins/maven-source-plugin/jar-no-fork-mojo.html) which does not invoke `generate-sources. ([more details](https://stackoverflow.com/questions/10567551/difference-between-maven-source-plugin-jar-and-jar-no-fork-goal#10568004))
==> it seems to work too :heavy_check_mark: 

**So I guess this is not a sortpom issue.**

**Comment by Ekryd** [comment]
I am glad that the problem was solved for you and thank you for posting it as an issue (in case somebody else stumbles on the same problem).
I guess that the IT test framework does some hacking in the Maven process. The IT tests themselves does not execute in the source directory, but it moves all files to the target/it directory before executing. Perhaps it also caches the pom file input instead of reading the pom between each phase??
