### ISSUE TITLE
Merge automatic pull requests automatically

### ISSUE THREAD

**Issue by Ekryd** [Ekryd/sortpom#254]
Sortpom tends to get a lot of automatic PRs from the dependabot, and 98% can be merged automatically. The junit tests are trusted, so if they pass the PR is safe to merge.

Just let the PRs that pass the build be merged automatically

**Comment by mccartney** [comment]
I have no experience with this particular action, but it seems like: https://github.com/marketplace/actions/dependabot-auto-merge would do the job.

**Comment by Ekryd** [comment]
I tried that one before, but could not get it to work. Do you know if any other repository is successfully using this?

**Comment by ppkarwasz** [comment]
If you use Github Actions, you can use `dependabot/fetch-metadata` followed by a call to `gh`.

Check [`logging-log4j-tools`](https://github.com/apache/logging-log4j-tools/blob/master/.github/workflows/build.yml) for an example.

**Comment by Ekryd** [comment]
Thanks for the tip, I’ll check it out

**Comment by Ekryd** [comment]
I made an implementation in https://github.com/Ekryd/echo-maven-plugin. Lets see how it works 🥳 
Then I'll do the same here

**Comment by Ekryd** [comment]
Worked like a charm. Let's see if it is just as effective here
