### ISSUE TITLE
Migrate from code.google.com

### ISSUE THREAD

**Issue by ctubbsii** [Ekryd/sortpom#30]
Since code.google.com is shutting down, I think it's really important that sortpom move to GitHub for its canonical location. I see this repository is already an export of what was in code.google.com, but it is not up-to-date.

Please update this repository, and migrate to GitHub, and provide a notice on code.google.com of the new location.

**Comment by Ekryd** [comment]
Don't worry! Right now I am waiting for Sonatype to approve the new artifact location in Maven central. https://issues.sonatype.org/browse/OSSRH-14439
After I have have moved the ReflectionUtils framework, I will move the SortPom plugin as well.

**Comment by Ekryd** [comment]
I have released a new version of the plugin. The functionality should be quite similar to 2.3.1, but with some updated libraries and updated location. Please try it out.
<plugin>
          <groupId>com.github.ekryd.sortpom</groupId>
          <artifactId>sortpom-maven-plugin</artifactId>
          <version>2.4.0</version>
          <configuration>
            <createBackupFile>false</createBackupFile>
            <predefinedSortOrder>custom_1</predefinedSortOrder>
            <lineSeparator>\n</lineSeparator>
            <encoding>${project.build.sourceEncoding}</encoding>
            <sortProperties>true</sortProperties>
            <keepBlankLines>true</keepBlankLines>
            <sortDependencies>scope</sortDependencies>
          </configuration>
        </plugin>

All thats left now is the documentation...

**Comment by Ekryd** [comment]
It took some time to get the code block right, sorry about that.

**Comment by ctubbsii** [comment]
For plugin documentation, I had decent luck setting up stuff on http://revelc.github.io/apilyzer-maven-plugin with my maven plugin: https://github.com/revelc/apilyzer-maven-plugin

**Comment by ctubbsii** [comment]
Also, thanks. I've just updated my project to use the 2.4.0 version here, and it works great.

**Comment by Ekryd** [comment]
Looks interesting. 
I know that I will get a lot of warnings from my use of JDom. I use some very shady side-effects of that framework in order to preserve comments and newlines... sad but true.
Good that you liked the new version! 
I will close this issue now
