### ISSUE TITLE
Generate plugin docs site

### ISSUE THREAD

**Issue by ctubbsii** [Ekryd/sortpom#33]
It'd be nice to generate plugin documentation, and publish in gh-pages. See https://github.com/revelc/zookeeper-maven-plugin for an example plugin which generates site docs and pushes to a gh-pages branch in GitHub.

**Comment by Ekryd** [comment]
Is it the site-plugin that generates the pages or does it collaborate with some other plugin?

**Comment by ctubbsii** [comment]
The maven-site-plugin generates the pages. Additional plugins are used to generate specific reports for the site. The zookeeper-maven-plugin example above uses maven-plugin-plugin to generate plugin reports, and maven-project-info-reports-plugin to generate basic project info for the site (links to issue tracker, source repo, authors, list of dependencies, etc.)

I use com.github.github:site-maven-plugin to publish the generated site to a gh-pages branch in github, but you can also just generate the site, and copy/upload the static content in target/site.

**Comment by Ekryd** [comment]
I am working on it. Right now I want to reduce the number of checkstyle warnings before I upload anything.

**Comment by Ekryd** [comment]
Getting closer... I just need a better internet connection (keep getting timeouts right now).
Have you found a way to generate a reference link to wiki-pages in the generated plugin information?

**Comment by Ekryd** [comment]
Hi,
The github site plugin does not work with multi-module projects, see https://github.com/github/maven-plugins/issues/22.
This means that the documentation for each module will overwrite each other. As the issue was created in 2012, I do not expect that it will be resolved.
It was an interesting experiment, but I will close this issue for now.
