### ISSUE TITLE
Add check goal

### ISSUE THREAD

**Issue by php-coder** [Ekryd/sortpom#34]
I would like to have a special `check` goal that won't change my `pom.xml` but will indicate is it already has sorted or hasn't.

Other plugins already have such feature:
- https://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html
- http://maven.apache.org/plugins/maven-pmd-plugin/check-mojo.html
- http://code.mycila.com/license-maven-plugin/#goals

**Comment by Ekryd** [comment]
HI
The following goal generates warnings during the build without resorting pom.xml:
mvn sortpom:verify -Dsort.verifyFail=warn
or if you want to stop the build without resorting:
mvn sortpom:verify -Dsort.verifyFail=stop

Does that solve your problem?

**Comment by JianbaoTao** [comment]
@Ekryd I am actually using the parameters you mentioned above to achieve exactly what @php-coder requested. However, there is one thing bugging me. Namely, the `verify` goal only checks the ordering of pom elements, but it doesn't check indent. I think we should take indent, and other relevant style issues, into account in the `verify` goal. In my opinion, a badly formatted pom is just as bad as a non-sorted pom.

**Comment by Ekryd** [comment]
@JianbaoTao The verify goal was created to let the user keep line breaks, i.e. if the pom-file was sorted by an IDE or contained custom formatting.
Do you need to just check the pom-file? Is it not easier to always sort the pom-file (to get both reordering and indents)?

**Comment by JianbaoTao** [comment]
@Ekryd I think it really depends on your style. If you don't want pom to be regenerated in every build but still want to make sure pom is nicely formatted, then `sortpom:verify` will fail this purpose.

**Comment by Ekryd** [comment]
@JianbaoTao The pom is only regenerated if it needs to be reordered with the sort goal. 
If the pom needs to be reordered the plugin outputs: 
[INFO] Sorting file /XXX/YYY/pom.xml
[INFO] Saved sorted pom file to /XXX/YYY/pom.xml

If the pom is already sorted the plugin outputs:
[INFO] Sorting file /XXX/YYY/pom.xml
[INFO] Pom file is already sorted, exiting
and leaves the original pom unchanged.

Do you stop the build or output warnings when you use the verify goal?

**Comment by JianbaoTao** [comment]
@Ekryd, thanks for the follow-up. We are actually using `sortpom` happily now.

**Comment by Ekryd** [comment]
No problem. I will close this issue for now. Regards, Björn
