### ISSUE TITLE
Setting to disable pom sorting?

### ISSUE THREAD

**Issue by sixcorners** [Ekryd/sortpom#343]
This might sound like kind of a stupid request but I mostly want to use sortPom in spotless to format the file. Think it would be possible to make a setting to not sort stuff? Thinking it could be like setting predefinedSortOrder to "none" or something. Not sure.

**Comment by Ekryd** [comment]
Interesting! Could you attach an unsorted and sorted file to experiment with?

**Comment by Ekryd** [comment]
Is this still an active request or should I close the issue?

**Comment by sixcorners** [comment]
I decided that if I just want xml formatting it makes better sense to use an xml formatter. Thanks though

**Comment by Ekryd** [comment]
No worries!
If formatting the xml is the issue, I agree that an xml formatter would be enough. If you want to reorder the xml structure (e.g making sure that the xml tags xxx always comes after tags yyy) then you are welcome to experiment with SortPom a bit more. Best of luck!
