### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brentvukmer** [Ekryd/sortpom#37]
This looks awesome.  Can you provide license information, please?  I'd like to use it at work.

**Comment by Ekryd** [comment]
It is awesome! :-)

The plugin is distributed with a 'New BSD License'.
https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29

I hope you like it.

**Comment by brentvukmer** [comment]
Can you include the license in the GitHub repo?  That's how the folks at my company validate whether we can use a library or not.

How is the license bundled with the plugin?

**Comment by Ekryd** [comment]
Added a license file to the Repo. The license information is also located in the pom.xml file of the root directory.

**Comment by brentvukmer** [comment]
Thanks!

**Comment by Ekryd** [comment]
NP
