### ISSUE TITLE
Line wrapping: Always use a 120-column line width.

### ISSUE THREAD

**Issue by stefaneicher** [Ekryd/sortpom#38]
how can is set the line with in sortpom?
see also 
https://maven.apache.org/developers/conventions/code.html

Gruss Stefan

**Comment by Ekryd** [comment]
Hi,

I can have a look at this. Do you have concrete example where a line in the pom-file is longer than 120 characters?

**Comment by stefaneicher** [comment]
Hi ,

yes it for example formats the pom header like this. All is on one Line.

[image: Inline-Bild 1]
or here
[image: Inline-Bild 2]

You can reproduce it here https://github.com/stefaneicher/democd just
checkout and run sortpom:sort.

Regards Stefan

2016-01-13 22:39 GMT+01:00 Björn Ekryd <notifications@github.com>:

**Comment by Ekryd** [comment]
The SortPom plugin is built on top of the JDom 1.1.3 library and that library does not have a line width option to format the xml. 
So unfortunately I cannot support line width in the plugin.

**Comment by mattnelson** [comment]
Logged a request to hunterhacker/jdom#170 for this feature.
