### ISSUE TITLE
Comment are moved on new line

### ISSUE THREAD

**Issue by ouaibsky** [Ekryd/sortpom#39]
Hi

I notes that xml file like this:
```xml
<foo>bla</foo> <!-- bar -->
```

after sorting is displayed like that:
```xml
<foo>bla</foo> 
<!-- bar -->
```

is there an option to avoid that (keep comment at end of line) ?
Thx
Christophe

**Comment by Ekryd** [comment]
Hi
The simple answer is that xml comments must always be placed before the tag it describes.
See [https://github.com/Ekryd/sortpom/wiki/Comments](https://github.com/Ekryd/sortpom/wiki/Comments)

If you really need (as in REALLY need) to keep the comments you can add ignore-sections 
[https://github.com/Ekryd/sortpom/wiki/IgnoringSections](https://github.com/Ekryd/sortpom/wiki/IgnoringSections)

Regards,
/Björn

**Comment by ouaibsky** [comment]
Thx for the explication.
If comment are kept before XML élément it's fine, but i remember having seen strange sorting, for instance in dependencies section. 

I'll retest this
Thx 
Christophe

**Comment by Ekryd** [comment]
If you find anything strange, I would be very glad if you could attach it to the issue so that I can fix it (or at least analyze it).
Regards,
/Björn
