### ISSUE TITLE
`mvn sortpom:sort` and `mvn verify` sort pom differently

### ISSUE THREAD

**Issue by jvarness** [Ekryd/sortpom#41]
How do I get the sortpom plugin to just use the configuration I define in my pom when I execute `mvn sortpom:sort`?

I've noticed that the plugin will use a different configuration. The most notable difference is the indentation is 3 when I execute `mvn verify` and it's set to 2 when I execute `mvn sortpom:sort`.

Can I get around having to edit the settings.xml file in my maven install?

**Comment by jvarness** [comment]
Here's my configuration, for reference:

```
<plugin>
        <groupId>com.github.ekryd.sortpom</groupId>
        <artifactId>sortpom-maven-plugin</artifactId>
        <version>2.4.0</version>
        <executions>
          <execution>
            <phase>verify</phase>
            <goals>
              <goal>verify</goal>
            </goals>
            <configuration>
              <nrOfIndentSpace>3</nrOfIndentSpace>
              <sortDependencies>scope,artifactId,groupId</sortDependencies>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by Ekryd** [comment]
I'm quite sure that it is because your configuration is inside the execution tag. Move the configuration directly under the plugin tag.

**Comment by jvarness** [comment]
http://i.makeagif.com/media/10-29-2013/1boaF8.gif

Thanks @Ekryd !

**Comment by Ekryd** [comment]
:-D
