### ISSUE TITLE
Revisit schema location indent choice

### ISSUE THREAD

**Issue by mches** [Ekryd/sortpom#413]
First, allow me to say thank you for SortPom.

The conscious choice of `2 * indent + 1 space` as a continuation indent seems to me an unusual one. In practice, I've only ever seen `2 * indent` or `1 * indent` continuation indents, no matter whether the indents are spaces or tabs. For that reason, how do you feel about standardizing on `2 * indent` as the continuation indent? Considering there's necessarily always a line separator before any continuation indent, that line separator alone substitutes for space as the obligatory whitespace between attributes, even when the indent is 0.

**Comment by mches** [comment]
> This might be a breaking change though (for those that use the parameter). All their pom-files will be resorted all of a sudden. Do you think that this should be a new major version of SortPom?

In a strict semantic versioning sense, I would say yes. As-is there's not even a config to keep the extra space, except say with the Spotless plugin. For what it's worth, I did notice between 3.3.x and 3.4.0 there was a binary-incompatible change in the sorter due to a changing method signature, which prevented upgrading for me until the next version of Spotless is released, but that signature change wasn't incompatible for the Sortpom plugin itself.  All in all, without any backward compatibility mitigations, I think there's a good argument for incrementing major version if you abide by semantic versioning with users' expectations in mind.

**Comment by Ekryd** [comment]
Sounds reasonable. Btw what do you use the sorter for? I have some future plans to merge the three SortPom maven modules into one, but if developers are using just the sorter, that might be a bad idea.

**Comment by mches** [comment]
> Sounds reasonable. 

On the other hand, I've used formatters like google-java-format and prettier that don't increment the major version, but rather the minor version, when the only the output changes. Notably both of these formatters are more opinionated and less configurable than SortPom. For these two formatters, the major version changes tend to be reserved for changing the minimum Java version, removing deprecations, removing formatters from core, etc. I'm just one user, but I plan to upgrade to the latest version whether it's a major or minor version upgrade.

> Btw what do you use the sorter for?

I'm using it [indirectly by way of Spotless](https://github.com/markitect-dev/markitect-liquibase/blob/b164fe1f97c49c80e21b0ca64ca047b146cbed8f/pom.xml#L220-L224). Spotless' [Gradle](https://github.com/diffplug/spotless/tree/53d03993d99e49e3d210b0d3bcacd6c4f546852a/plugin-gradle#maven-pom) and [Maven](https://github.com/diffplug/spotless/tree/f7346d52882df5b0eb9f8eb7c13aea8ec14c43f6/plugin-maven#maven-pom) plugins support formatting Maven POMs. Actually, I [added the Gradle support](https://github.com/diffplug/spotless/pull/2082) which has not been released yet. [SortPomFormatterFunc](https://github.com/diffplug/spotless/blob/7262511a9d66e272d1053146c033499e89383bf0/lib/src/sortPom/java/com/diffplug/spotless/glue/pom/SortPomFormatterFunc.java) has a direct dependency on your sorter.

**Comment by Ekryd** [comment]
Released new version

**Comment by mches** [comment]
Thanks and congrats! I already submitted a [PR](https://github.com/diffplug/spotless/pull/2115) to Spotless to update to 4.0.0.

**Comment by Ekryd** [comment]
I really appreciate your contributions. I’ll check out the PR

**Comment by mches** [comment]
I was finally able to [use sortpom-sorter 4.0.0 with spotless-maven-plugin 2.44.0.BETA1 and remove all my indentation workarounds](https://github.com/markitect-dev/markitect-liquibase/compare/9fa4373a...45b05c1a). Thanks again

**Comment by Ekryd** [comment]
That is great to hear. Please enjoy!!
