### ISSUE TITLE
Can this be configured to fail if not formatted correctly?

### ISSUE THREAD

**Issue by JLLeitschuh** [Ekryd/sortpom#42]
If a user modifies the pom but forgets to sort it (ie. doesn't run a build locally like they should) I'd like our CI system to fail the build.
Is this something that can be configured?

**Comment by Ekryd** [comment]
Sure thing. Have a look at the verify goal: https://github.com/Ekryd/sortpom/wiki/Parameters#for-the-verify-goal
Does that solve your problem?

**Comment by JLLeitschuh** [comment]
It does! Thanks!!!

**Comment by Ekryd** [comment]
No problem. Glad you like the plugin!

**Comment by JLLeitschuh** [comment]
What's more important is that our companies build engineer likes the idea of using this plugin.
Thanks for being so responsive!
