### ISSUE TITLE
Support different output formats

### ISSUE THREAD

**Issue by php-coder** [Ekryd/sortpom#44]
I'm using sortpom-maven-plugin to only check the pom.xml when a new PR is submitted. I didn't find a way to get the messages in the machine-readable form (XML/JSON). It would be great to have such feature because it could be used in automatization and integration with external plugins/bots.

**Comment by Ekryd** [comment]
This sounds like a good idea. Could you give me an example of how you would like the output to look like?

**Comment by php-coder** [comment]
I'm suggesting something like this (inspired by the CheckStyle/PMD reports):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sortpom version="2.5.0">
    <violation line="19">
        The xml element &lt;groupId&gt;com.github.heneke.thymeleaf&lt;/groupId&gt; should be placed before &lt;groupId&gt;javax.validation&lt;/groupId&gt;
    </violation>
</sortpom>
```
If it's possible the `column` and `rule` attributes could be added too.

**Comment by Ekryd** [comment]
There are (at least) two ways to do this. 
Do you mean that you run the plugin as normal but specify that the output should be sent to a external file or do you want the run the plugin under the reporting section of the pom.xml?

See example of the two different ways at https://maven.apache.org/plugins/maven-pmd-plugin/usage.html

**Comment by php-coder** [comment]
> Do you mean that you run the plugin as normal but specify that the output should be sent to a external file or do you want the run the plugin under the reporting section of the pom.xml?

The first option. I'd like to have output on the console as well as in the file (that later could be parsed).

**Comment by Ekryd** [comment]
Great! I will make some changes and we will see if you like it. Disclaimer: this is done on my spare time, so I can't promise a specific delivery date.

**Comment by Ekryd** [comment]
Normally if the plugin is configured in the pom-file or run with 
mvn sortpom:verify -Dsort.verifyFail="Warn"

The output to the console would be
[INFO] --- sortpom-maven-plugin:2.4.0:verify (default-cli) @ sortpom-parent ---
[INFO] Verifying file /path/pom.xml
[WARNING] The xml element <version> should be placed before <packaging>
[WARNING] The file /path/pom.xml is not sorted

New way would be be a configuration like
mvn sortpom:verify -Dsort.verifyFail="Warn" -Dsort.outputType="console, file" 
-Dsort.outputFile="sortpom-reports/sortpom-result.xml"

The output to the console would be the same and the the output to the file would be
<?xml version="1.0" encoding="UTF-8"?>
<sortpom version="2.6.0">
    <information>Verifying file /path/pom.xml</information>
    <warning>The xml element &lt;version&gt; should be placed before &lt;packaging&gt;</warning>
    <warning>The file /path/pom.xml is not sorted</warning>
</sortpom>

Would this be enough or should the the output be more customised?

**Comment by php-coder** [comment]
> Verifying file /path/pom.xml
> The xml element <version> should be placed before <packaging>
> The file /path/pom.xml is not sorted
> Would this be enough or should the the output be more customised?

I believe that the first and the last lines aren't so useful because they doesn't contain actual violations. Could we omit them? Also, this output will be in XML/JSON form or am I missing something here?

**Comment by Ekryd** [comment]
Wtf! My xml example just vanished! This is how it should have looked

The output to the console would be the same and the the output to the file would be
```
<?xml version="1.0" encoding="UTF-8"?>
<sortpom version="2.6.0">
    <information>Verifying file /path/pom.xml</information>
    <warning>The xml element &lt;version&gt; should be placed before &lt;packaging&gt;</warning>
    <warning>The file /path/pom.xml is not sorted</warning>
</sortpom>
```

**Comment by Ekryd** [comment]
If the following command was run: 
mvn sortpom:verify -Dsort.verifyFail="Warn" -Dsort.outputType="console, file"
-Dsort.outputFile="sortpom-reports/sortpom-result.xml"

The console output would be
[INFO] --- sortpom-maven-plugin:2.4.0:verify (default-cli) @ sortpom-parent ---
[INFO] Verifying file /path/pom.xml
[WARNING] The xml element should be placed before 
[WARNING] The file /path/pom.xml is not sorted

and the file output (./target/sortpom-reports/sortpom-result.xml) would be
`<?xml version="1.0" encoding="UTF-8"?>
<sortpom version="2.6.0">
  <file name="c:\path\pom.xml">
    <violation goal="verify">The xml element &lt;version&gt; should be placed before &lt;packaging&gt;</violation>
  </file>
</sortpom>`

I would like to keep the file indicator, but is the goal attribute really necessary?
Unfortunately I can only report one violation for the pom.xml.

What would the xml look like when everything is ok, just the sortpom and file tag?
I think that the console output should only be available to the verify goal, thoughts?
The violation entry will be written no matter what the verifyFail option says, right?

**Comment by php-coder** [comment]
>I would like to keep the file indicator, but is the goal attribute really necessary?

Yes, I agree that `goal` attribute isn't necessary (at least to me :))

>What would the xml look like when everything is ok, just the sortpom and file tag?

I expect that the report file isn't created at all.

>The violation entry will be written no matter what the verifyFail option says, right?

Sounds reasonable.

**Comment by Ekryd** [comment]
Good! Then I will start to look at the code and see how this can be realized. I will keep you posted when I have done some progress.

**Comment by Ekryd** [comment]
Added a new branch with the new functionality. 
The new parameter would be used like this:
`mvn sortpom:verify -Dsort.violationFilename="target/sortpom_reports/violation.xml"`

and the output would be like this:
`<?xml version="1.0" encoding="UTF-8"?>
<sortpom>
  <file filename="/Users/bjorn/Workspace/SortPom/maven-plugin/target/it/violation-file/pom.xml">
    <violation>The xml element &lt;modelVersion&gt; should be placed before &lt;name&gt;</violation>
  </file>
</sortpom>`

**Comment by Ekryd** [comment]
I will continue with some more tests.

**Comment by Ekryd** [comment]
Finally I have gotten some time to code properly! 
Question:
Should the violation file be overwritten automatically if it already exists? Or should the plugin stop directly? Or stop just when it is about to write to the file? 
My thoughts is that the plugin should stop directly, so that an existing violation file cannot give a false impression that the build failed. Or should an old file be deleted if the verification was ok?

**Comment by php-coder** [comment]
I would expect that file will be overwritten. When there is no violations then report won't have them.

**Comment by Ekryd** [comment]
Overwrite works for me. Just to clarify: If the verify passed and an old violation file exists, will it be deleted or will it be left alone?

**Comment by php-coder** [comment]
It should be overwritten by empty report:
```
<?xml version="1.0" encoding="UTF-8"?>
<sortpom>
  <file filename="/Users/bjorn/Workspace/SortPom/maven-plugin/target/it/violation-file/pom.xml">
  </file>
</sortpom>
```

**Comment by Ekryd** [comment]
Lets see:

I can think of two scenarios where the violation file will be left by the build.
1. Optimized Jenkins build where the target directory is cleaned seldom to improve build speed.
In this case the violation file should be cleared or emptied.
2. Deployment with some sort release plugin where the same phases run again and again.
In this case the violation file should be kept to indicate that the pom-file caused a violation at some point in the build.

I think that I will solve the problem as I handle the backup file. Write the violation file only if an violation occurred. Overwrite old file if violation occurs, otherwise just leave the disk drive as it is. This will be the easiest to implement/test. Any problems with leftover violation files will have to be solved by the user of the plugin. Would that work for you?

**Comment by Ekryd** [comment]
Hi
I have made an implementation that is on the master branch. Could you please try it out by downloading the code, build it with `mvn clean install`, and run it with `mvn com.github.ekryd.sortpom:sortpom-maven-plugin:2.6.1-SNAPSHOT:verify -Dsort.violationFilename="target/sortpom_reports/violation.xml"`?
Feel free to try out your use case and any corner cases.

**Comment by php-coder** [comment]
Ok, I'll try it this weekend. Thanks!

**Comment by php-coder** [comment]
It worked for me, thanks!

**Comment by Ekryd** [comment]
Released version 2.7.0 with the new functionality. Will update the wiki documentation soon.

**Comment by Ekryd** [comment]
Added some documentation to the parameter wiki. Have you tried the official version yet?

**Comment by php-coder** [comment]
No, I've added it to my todo list :)

**Comment by Ekryd** [comment]
I know that feeling ;-)
