### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by bguerin** [Ekryd/sortpom#53]
Hello,

You could please release your plugin, I look forward to use the "force EOL" feature !

Thanks !

**Comment by Ekryd** [comment]
As soon as I am able. Work is killing me at the moment :-/

**Comment by Ekryd** [comment]
Hi. 
Plugin version 2.6.0 should be available right now. 
It takes a while for the Maven Central Search to discover it, but mvn com.github.ekryd.sortpom:sortpom-maven-plugin:2.6.0:sort should work.
Documentation for the plugin should also be updated.

Sorry for the delay, mate.

**Comment by bguerin** [comment]
Yeah !!!! Thanks !
