### ISSUE TITLE
Keep namespace declarations on different lines

### ISSUE THREAD

**Issue by andybergon** [Ekryd/sortpom#56]
Is there a way to keep the namespace declarations on different lines and not have those be merged in one line?

![screenshot at jun 22 16-27-39](https://user-images.githubusercontent.com/5220825/27443164-194abf82-576a-11e7-9e2b-19c20c5e3858.png)

**Comment by bguerin** [comment]
See #55

**Comment by andybergon** [comment]
Ok, so unfortunately we can't do anything about that 😢
