### ISSUE TITLE
Empty line between dependencies scopes

### ISSUE THREAD

**Issue by jdavis4452** [Ekryd/sortpom#57]
I was curious if it would be possible to have the plugin add empty lines between dependencies scopes?

Currently my team does this...
-Dsort.sortDependencies=scope,groupId,artifactId

It would be nice if it would put an empty line between the last dependency of each scope.

Something like this...

```
<dependency>
	<groupId>com.common.foo</groupId>
	<artifactId>foo</artifactId>
	<version>1.3.2</version>
	<scope>compile</scope>
</dependency>

<dependency>
	<groupId>com.common.foo2</groupId>
	<artifactId>foo2</artifactId>
	<version>2.7</version>
	<scope>test</scope>
</dependency>
```

Previously we were putting comments between them but once we started using this plugin the comments would sometimes be out of place after sorting.
Just make it easier to see when the scope changes.

**Comment by bguerin** [comment]
Do it by hand once, and it will be kept

**Comment by jdavis4452** [comment]
Cool thanks.

**Comment by Ekryd** [comment]
Just make sure that you have the option keepBlankLines set to true.

**Comment by jdavis4452** [comment]
Yeah I do. Thanks!
