### ISSUE TITLE
lineLength not preserved everywhere

### ISSUE THREAD

**Issue by Kidlike** [Ekryd/sortpom#63]
I have a lineLength of 160, and this line isn't wrapped, even though it's 205 chars.
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```

Possibly also introduce another config, wrap-attributes. Potential config values "do not wrap", "wrap if long", "always wrap".

**Comment by Ekryd** [comment]
This plugin does not have a lineLength setting. So, what is the problem?

**Comment by Kidlike** [comment]
Oh, interesting... IntelliJ IDEA thinks it does for some reason !

I assumed there's an XSD somewhere that defines the parameters and intellij grabbed it, because all the rest parameters displayed when I do auto-complete are correct.

The problem is that IntelliJ changes the pom.xml file when I run the reformat-code action.
So there's a conflict between the IntelliJ settings and the sortpom settings.

I can change the IntelliJ settings of course, but I would prefer if sortpom had a parameter for this.

**Comment by Kidlike** [comment]
This is what IntelliJ grabs: [sortpom-maven-plugin-decsription.xml.txt](https://github.com/Ekryd/sortpom/files/1887174/sortpom-maven-plugin-decsription.xml.txt)

It resides in this path:
```
sortpom-maven-plugin-2.8.0.jar/META-INF/maven/plugin.xml
```

If you search for `lineLength` it exists...

```
<parameter>
    <name>lineLength</name>
    <type>int</type>
    <required>false</required>
    <editable>true</editable>
    <description>The maximum length of a display line, should be positive.</description>
</parameter>
```

**Comment by Kidlike** [comment]
Also I found there's a help goal, which also lists `lineLength`.

```
$ mvn sortpom:help -Ddetail=true -o | grep -i linelength
    lineLength (Default: 80)
      User property: lineLength
```

**Comment by Ekryd** [comment]
I think I have found the source of the confusion. 
All maven plugins have a default 'help' goal and that goal has a lineLength parameter.
Basically you can run `mvn sortpom:help -Ddetail=true -DlineLength=50` to force the help text to be displayed with line length of 50 characters.

IntelliJ picks up this parameter in the intellisense. If you check the plugin configuration for ANY maven plugin you will discover that they all have lineLength parameter.

The goals sort and verify do not have that parameter. See #38

**Comment by Kidlike** [comment]
I see... thanks :)
