### ISSUE TITLE
Ignore/Resume issue is dependency after block is moved

### ISSUE THREAD

**Issue by nhojpatrick** [Ekryd/sortpom#76]
This is an extract of the pom I had. Due to jmockit issues it needs to be the 1st dependency, so I'm using `<?SORTPOM IGNORE?>` and `<?SORTPOM RESUME?>` to pin it to the top of `<dependencies>`;
```
	<dependencies>
		<?SORTPOM IGNORE?>
		<dependency>
			<groupId>org.jmockit</groupId>
			<artifactId>jmockit</artifactId>
			<scope>test</scope>
		</dependency>
		<?SORTPOM RESUME?>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

I've got this user property set `<sort.sortDependencies>groupId,artifactId,version,scope</sort.sortDependencies>`.

After execution this is the result;
```
	<dependencies>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<?SORTPOM IGNORE?>
		<dependency>
			<groupId>org.jmockit</groupId>
			<artifactId>jmockit</artifactId>
			<scope>test</scope>
		</dependency>
		<?SORTPOM RESUME?>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

If I reorder so the dependency that needs reordering is not directly after `<?SORTPOM RESUME?>` then it reorders correctly.

From my experiments, it looks like `<?SORTPOM IGNORE?>` and `<?SORTPOM RESUME?>` are treated like comments when reordering.

So;
```
	<dependencies>
		<?SORTPOM IGNORE?>
		<dependency>
			<groupId>org.jmockit</groupId>
			<artifactId>jmockit</artifactId>
			<scope>test</scope>
		</dependency>
		<?SORTPOM RESUME?>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

Reorders as expected;
```
	<dependencies>
		<?SORTPOM IGNORE?>
		<dependency>
			<groupId>org.jmockit</groupId>
			<artifactId>jmockit</artifactId>
			<scope>test</scope>
		</dependency>
		<?SORTPOM RESUME?>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

**Comment by nhojpatrick** [comment]
I've attempted a patch, as I've tried hunting the code to understand how reordering is done but I don't fully understand that logic.

**Comment by Ekryd** [comment]
Hi! I believe that you right, they are treated like comments. Have you tried to create a custom sort order? If you specify a dependency in the custom sort order then it will be put at the top. 
What happens if the dependency is put lower down?

**Comment by Ekryd** [comment]
There is a simple solution to your problem. Just sort the file once (without SORTPOM IGNORE) and then place the the ignored dependency at the top. The ignored dependency will then always be above the top-most dependency.

```
  <dependencies>
    <?SORTPOM IGNORE?>
    <dependency>
       <groupId>org.jmockit</groupId>
       <artifactId>jmockit</artifactId>
       <scope>test</scope>
       <version>1.49</version>
    </dependency>
    <?SORTPOM RESUME?>
    <dependency>
      <groupId>org.hamcrest</groupId>
      <artifactId>hamcrest</artifactId>
      <version>LATEST</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>LATEST</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <version>3.4.4</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>com.github.ekryd.sortpom</groupId>
        <artifactId>sortpom-maven-plugin</artifactId>
        <version>2.12.0</version>
        <configuration>
          <createBackupFile>false</createBackupFile>
          <predefinedSortOrder>custom_1</predefinedSortOrder>
          <lineSeparator>\n</lineSeparator>
          <sortProperties>true</sortProperties>
          <keepBlankLines>true</keepBlankLines>
          <sortDependencies>groupId,artifactId,version,scope</sortDependencies>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

Would that solve your problem?

**Comment by nhojpatrick** [comment]
Doing a manual sort would always fix most sort issue.

Can you point me to the documentation about how to hard code a dependency in the sort order file... Otherwise I mis-understood the comment about using a custom sort order file.

**Comment by Ekryd** [comment]
There seems to be documentation lacking for this, my bad. I will have to fix that.
I am very busy at the moment, so it will take a while to do the documentation. Let me get back to you in about 2 weeks.

**Comment by Ekryd** [comment]
I'm back and looking into this issue again

**Comment by Ekryd** [comment]
Hi,
I could no longer find the way to insert dependencies in the sort order file, it must have been a long time ago that that was possible. 

Your IGNORE-magic work like this: 
if the sortDependencies parameter is set to scope, groupId and/or artifactId, then the ignored dependency will always be put at the top. This is due to the fact that SortPom does not see the ignored content and empty content will always be *less* than non-empty content.

I added this to the ignore section wiki page, as well as an integration test for this. https://github.com/Ekryd/sortpom/wiki/IgnoringSections#critical-dependencies-to-the-top

Could you please have a look at the wiki page.

**Comment by nhojpatrick** [comment]
documentation looks good covering this situation...
