### ISSUE TITLE
sort executions

### ISSUE THREAD

**Issue by delanym** [Ekryd/sortpom#81]
Can this be done? Suggest order alphabetical by id.

**Comment by Ekryd** [comment]
Hi, 
Please give me an concrete example of what you want to do

**Comment by delanym** [comment]
Given

```
<plugin>
  <groupId>of.toad.hall</groupId>
  <artifactId>toad</artifactId>
  <executions>
    <execution>
      <id>03-flight-from-the-weasels</id>
      <phase>validate</phase>
      <goals>
        <goal>exec</goal>
      </goals>
    </execution>
    <execution>
      <id>adventures</id>
      <phase>validate</phase>
      <goals>
        <goal>exec</goal>
      </goals>
    </execution>
    <execution>
      <id>02-escape</id>
      <phase>validate</phase>
      <goals>
        <goal>exec</goal>
      </goals>
    </execution>
    <execution>
      <id>01-imprisonment</id>
      <phase>validate</phase>
      <goals>
        <goal>exec</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

return

```
<plugin>
  <groupId>of.toad.hall</groupId>
  <artifactId>toad</artifactId>
  <executions>
    <execution>
      <id>01-imprisonment</id>
      <phase>validate</phase>
      <goals>
        <goal>exec</goal>
      </goals>
    </execution>
    <execution>
      <id>02-escape</id>
      <phase>validate</phase>
      <goals>
        <goal>exec</goal>
      </goals>
    </execution>
    <execution>
      <id>03-flight-from-the-weasels</id>
      <phase>validate</phase>
      <goals>
        <goal>exec</goal>
      </goals>
    </execution>
    <execution>
      <id>adventures</id>
      <phase>validate</phase>
      <goals>
        <goal>exec</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

**Comment by Ekryd** [comment]
Should be possible, but I don't really see the need to create a sort order based on the id.
On the other hand, just resorting the executions by phase could be a help when developing. 

But... Do you have a project that has multiple executions (in different phases or same phase) for one plugin?

**Comment by delanym** [comment]
Yes, it my case it would be helpful. Its the only thing left that doesn't get sorted, and it affects the build order. I want my build to be free from any implicit order based on the arrangement of the xml file.

**Comment by Ekryd** [comment]
The sort order would be like this falling order:
(first)
no phase and no id
no phase and id (sorted by id value)
standard phase and no id (sorted by Maven phase order)
standard phase and id (sorted by Maven phase order and then id value)
other phase and no id (sorted by phase value)
other phase and id (sorted by phase value and then id value).

Given:
`
                <executions>
                    <execution>
                        <phase>tomato</phase>
                    </execution>
                    <execution>
                        <phase>test</phase>
                    </execution>
                    <execution>
                        <phase>install</phase>
                    </execution>
                    <execution>
                        <phase>pre-CLEAN</phase>
                    </execution>
                    <execution>
                        <phase>site</phase>
                    </execution>
                    <execution>
                        <phase>package</phase>
                    </execution>
                    <execution>
                        <id>c</id>
                        <phase>compile</phase>
                    </execution>
                    <execution>
                        <id>b</id>
                        <phase/>
                    </execution>
                    <execution>
                        <id>c</id>
                    </execution>
                    <execution>
                        <id>a</id>
                    </execution>
                    <execution>
                        <goals>nope</goals>
                    </execution>
`
returns
`
        <executions>
          <execution>

            <goals>nope</goals>
          </execution>
          <execution>

            <id>a</id>
          </execution>
          <execution>
            <id>c</id>
          </execution>
          <execution>

            <phase>pre-CLEAN</phase>
          </execution>
          <execution>
            <id>c</id>
            <phase>compile</phase>
          </execution>
          <execution>
            <phase>test</phase>
          </execution>
          <execution>
            <phase>package</phase>
          </execution>
          <execution>
            <phase>install</phase>
          </execution>
          <execution>
            <phase>site</phase>
          </execution>
          <execution>

            <id>b</id>
            <phase></phase>
          </execution>
          <execution>
            <phase>tomato</phase>
          </execution>
        </executions>
`

**Comment by Ekryd** [comment]
Time for testing!

- Clone the repository
- Checkout the branch issue-81-sort_executions
- Build with mvn clean install
- Use the plugin with mvn com.github.ekryd.sortpom:sortpom-maven-plugin:2.12.1-SNAPSHOT:sort and remember to use the new parameter -Dsort.sortExecutions=true or false
 
Let me know how it works for you

**Comment by Ekryd** [comment]
And also Merry Christmas and A Happy New Year!! 🥳🎉

**Comment by delanym** [comment]
Merry Christmas!

There's an error on building **mojo-description/pom.xml**

    The post-build script did not succeed. assert log.text.replaceAll('\r','').contains(expected_log.text.replaceAll('@pom.version@', projectversion).replaceAll('\r',''))

**Comment by Ekryd** [comment]
I’ll have a look as soon as possible. Which OS are you using?

**Comment by delanym** [comment]
Ubuntu

**Comment by Ekryd** [comment]
HI, I checked Travis and the build failed once under JDK 12 (but the other JDKs were fine). I have tried to reproduce it at home (on Mac with different JDKs) but everything seems to run ok. 
I guess that you have the latest updates on the branch? 
Can you go to SortPom/maven-plugin/target/it/mojo-description and diff the files build.log and expected.log with each other to see the differences. I suspect end of line differences.

**Comment by delanym** [comment]
I had threading turned on in /etc/maven/logging/simplelogger.properties
The plugin does exactly what I asked for so closing this.

A very organised if I might say. I'm learning from your use of other plugins.

**Comment by Ekryd** [comment]
Great! I will solve another issue and then release an official version.

**Comment by Ekryd** [comment]
Hi!

New official release 2.13.1 has the sortExecutions option.

**Comment by Ekryd** [comment]
Updated the documentation for the plugin. https://github.com/Ekryd/sortpom/wiki/Parameters
Have you tried the official version yet?
