### ISSUE TITLE
sort by value for non-pom

### ISSUE THREAD

**Issue by delanym** [Ekryd/sortpom#84]
Im using this to sort my .mvn/extensions.xml file.
I understand I should configure a sortOrderFile, like default_1_0_0.xml, and adapt it to match the elements in the extensions.xml file.

But even with that file I wonder how it will manage to sort the extensions by "groupId, artifactId", since to achieve this in a pom requires a configuration <sortPlugins>groupId,artifactId</sortPlugins>?

I tried making another execution anyway without any extra config and it managed to sort the extensions by artifactId.

**Comment by delanym** [comment]
Not that it matters too much in the extensions.xml file—more important to sort these elements (there are hundreds of them):

    //plugin[artifactId="maven-dependency-plugin"]/executions/execution/configuration/artifactItems/artifactItem ordered by "groupId,artifactId"

**Comment by Ekryd** [comment]
Sorry, I won't have the time to write custom sort for other file types.

**Comment by delanym** [comment]
That's fine, but how to sort plugin configuration in a pom?

**Comment by Ekryd** [comment]
Quick answer: they are not sorted ;-)
I don't know if some plugins rely on the configuration being in a specific order
