### ISSUE TITLE
Comments after a xml tag is formatted wrong.

### ISSUE THREAD

**Issue by martinaldrin** [Ekryd/sortpom#86]
Please see attached screenshot.  
It looks like the formatter have a predefined max number of characters per line. I would prefer if it would be possible to disable that or that the comment are added before the xml tag instead of after. Also tabs are not replaced with spaces.

![image](https://user-images.githubusercontent.com/3080866/106599212-08db0c00-6559-11eb-906c-376f806b05b5.png)

**Comment by Ekryd** [comment]
Hi,

SortPom wants comments to be placed before a tag, see https://github.com/Ekryd/sortpom/wiki/Comments
Also the content inside a comment is not modified in any way, so no magic line breaks. In your example, the content in your comments is actually unmodified.
